//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalExpenseCreditTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalExpenseCreditTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap arrowhead_up {
            get {
                object obj = ResourceManager.GetObject("arrowhead-up", resourceCulture);
=======
        internal static System.Drawing.Bitmap fast_forward_double_right_arrows_symbol {
            get {
                object obj = ResourceManager.GetObject("fast-forward-double-right-arrows-symbol", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap bell {
            get {
                object obj = ResourceManager.GetObject("bell", resourceCulture);
=======
        internal static System.Drawing.Bitmap fast_forward_double_right_arrows_symbol__1_ {
            get {
                object obj = ResourceManager.GetObject("fast-forward-double-right-arrows-symbol (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap borrowing {
            get {
                object obj = ResourceManager.GetObject("borrowing", resourceCulture);
=======
        internal static System.Drawing.Bitmap file_export {
            get {
                object obj = ResourceManager.GetObject("file-export", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap borrowing_white {
            get {
                object obj = ResourceManager.GetObject("borrowing-white", resourceCulture);
=======
        internal static System.Drawing.Bitmap file_export__1_ {
            get {
                object obj = ResourceManager.GetObject("file-export (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
=======
        internal static System.Drawing.Bitmap file_export__2_ {
            get {
                object obj = ResourceManager.GetObject("file-export (2)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap cogwheel {
            get {
                object obj = ResourceManager.GetObject("cogwheel", resourceCulture);
=======
        internal static System.Drawing.Bitmap Gave_Money {
            get {
                object obj = ResourceManager.GetObject("Gave Money", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap cogwheel__1_ {
            get {
                object obj = ResourceManager.GetObject("cogwheel (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap man {
            get {
                object obj = ResourceManager.GetObject("man", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap credit_card {
            get {
                object obj = ResourceManager.GetObject("credit-card", resourceCulture);
=======
        internal static System.Drawing.Bitmap money_transfer__1_ {
            get {
                object obj = ResourceManager.GetObject("money-transfer (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap credit_card_white {
            get {
                object obj = ResourceManager.GetObject("credit-card-white", resourceCulture);
=======
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
=======
        internal static System.Drawing.Bitmap next__1_ {
            get {
                object obj = ResourceManager.GetObject("next (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap handshake {
            get {
                object obj = ResourceManager.GetObject("handshake", resourceCulture);
=======
        internal static System.Drawing.Bitmap next__1_1 {
            get {
                object obj = ResourceManager.GetObject("next (1)1", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
=======
        internal static System.Drawing.Bitmap next_page {
            get {
                object obj = ResourceManager.GetObject("next-page", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap home_white {
            get {
                object obj = ResourceManager.GetObject("home_white", resourceCulture);
=======
        internal static System.Drawing.Bitmap next_page__1_ {
            get {
                object obj = ResourceManager.GetObject("next-page (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap home2 {
            get {
                object obj = ResourceManager.GetObject("home2", resourceCulture);
=======
        internal static System.Drawing.Bitmap Payment_Due {
            get {
                object obj = ResourceManager.GetObject("Payment Due", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap home3 {
            get {
                object obj = ResourceManager.GetObject("home3", resourceCulture);
=======
        internal static System.Drawing.Bitmap Payment_Transaction {
            get {
                object obj = ResourceManager.GetObject("Payment Transaction", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap Home4 {
            get {
                object obj = ResourceManager.GetObject("Home4", resourceCulture);
=======
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap Home5 {
            get {
                object obj = ResourceManager.GetObject("Home5", resourceCulture);
=======
        internal static System.Drawing.Bitmap refresh__1_ {
            get {
                object obj = ResourceManager.GetObject("refresh (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap Home6 {
            get {
                object obj = ResourceManager.GetObject("Home6", resourceCulture);
=======
        internal static System.Drawing.Bitmap rupee {
            get {
                object obj = ResourceManager.GetObject("rupee", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap home7 {
            get {
                object obj = ResourceManager.GetObject("home7", resourceCulture);
=======
        internal static System.Drawing.Bitmap rupee__1_ {
            get {
                object obj = ResourceManager.GetObject("rupee (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap house_regular__1_ {
            get {
                object obj = ResourceManager.GetObject("house-regular (1)", resourceCulture);
=======
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap moon {
            get {
                object obj = ResourceManager.GetObject("moon", resourceCulture);
=======
        internal static System.Drawing.Bitmap save__1_ {
            get {
                object obj = ResourceManager.GetObject("save (1)", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap night_mode {
            get {
                object obj = ResourceManager.GetObject("night-mode", resourceCulture);
=======
        internal static System.Drawing.Bitmap Total_Due {
            get {
                object obj = ResourceManager.GetObject("Total Due", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< Updated upstream
        internal static System.Drawing.Bitmap payment_3948571 {
            get {
                object obj = ResourceManager.GetObject("payment_3948571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_lent {
            get {
                object obj = ResourceManager.GetObject("payment-lent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_lent1 {
            get {
                object obj = ResourceManager.GetObject("payment-lent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payment_white {
            get {
                object obj = ResourceManager.GetObject("payment-white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil__2_ {
            get {
                object obj = ResourceManager.GetObject("pencil (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil_white {
            get {
                object obj = ResourceManager.GetObject("pencil-white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap task {
            get {
                object obj = ResourceManager.GetObject("task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap task__white {
            get {
                object obj = ResourceManager.GetObject("task -white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wallet_ {
            get {
                object obj = ResourceManager.GetObject("wallet ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wallet_filled_money_tool {
            get {
                object obj = ResourceManager.GetObject("wallet-filled-money-tool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wallet_filled_money_tool1 {
            get {
                object obj = ResourceManager.GetObject("wallet-filled-money-tool1", resourceCulture);
=======
        internal static System.Drawing.Bitmap Total_Lent {
            get {
                object obj = ResourceManager.GetObject("Total Lent", resourceCulture);
>>>>>>> Stashed changes
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
