CREATE TABLE Lent(
	Lent_ID INT PRIMARY KEY IDENTITY(1,1),
	User_ID INT NOT NULL,
	Person_ID INT NOT NULL,
	Payment_ID INT NOT NULL,
	Status_ID INT NOT NULL,
	Amount DECIMAL(10,2) NOT NULL,
	Lent_at DATETIME NOT NULL,
	Return_at DATETIME NOT NULL,
	Description VARCHAR(255) NOT NULL
	);