CREATE TABLE tblLent(
	LentID INT PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	PersonID INT NOT NULL,
	PaymentID INT NOT NULL,
	StatusID INT NOT NULL,
	Amount DECIMAL(10,2) NOT NULL,
	ReturnedAmount DECIMAL(10,2) NOT NULL,
	RemainingAmount DECIMAL(10,2) NOT NULL,
	LentAt DATETIME NOT NULL DEFAULT GETDATE(),
	DeadlineAt DATETIME,
	Description VARCHAR(MAX) NOT NULL,

	FOREIGN KEY (UserID) REFERENCES tblUsers(UserID),
	FOREIGN KEY (PersonID) REFERENCES tblPersons(PersonID),
	FOREIGN KEY (PaymentID) REFERENCES tblPaymentType(PaymentID),
	FOREIGN KEY (StatusID) REFERENCES tblLentBorrowStatus(StatusID)
);
