CREATE TABLE tblPersons (
    PersonID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    PersonName VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Address VARCHAR(MAX) NULL,

    FOREIGN KEY (UserID) REFERENCES tblUsers(UserID)
);
